Added deferred expressions for wire
xsuite/xtrack pull request #162
Opened 2022-04-08 19:26 UTC by pbelange

2022-04-09 11:59 UTC, giadarol requested changes

2022-04-09 11:59 UTC, giadarol commented on tests/.ipynb_checkpoints/test_elements-checkpoint.py
> +import numpy as np
I believe this file was added by mistake. --> To be removed

2022-04-09 11:59 UTC, giadarol commented on xtrack.egg-info/SOURCES.txt
> +MANIFEST.in
This file was added by mistake, it should be removed

2022-04-09 11:59 UTC, giadarol commented on xtrack.egg-info/dependency_links.txt
> +
This file was added by mistake, it should be removed

2022-04-09 11:59 UTC, giadarol commented on xtrack.egg-info/requires.txt
> +numpy>=1.0
This file was added by mistake, it should be removed

2022-04-09 11:59 UTC, giadarol commented on xtrack.egg-info/top_level.txt
> +ducktrack
This file was added by mistake, it should be removed

2022-04-09 11:59 UTC, giadarol commented on xtrack/.ipynb_checkpoints/loader_mad-checkpoint.py
> +import numpy as np
This file was added by mistake, it should be removed

2022-04-09 11:59 UTC, giadarol commented on xtrack/beam_elements/.ipynb_checkpoints/elements-checkpoint.py
> +from pathlib import Path
This file was added by mistake, it should be removed

2022-04-09 11:59 UTC, giadarol commented on xtrack/beam_elements/elements_src/.ipynb_checkpoints/wire-checkpoint.h
> +#ifndef XTRACK_WIRE_H
This file was added by mistake, it should be removed

2022-04-11 17:49 UTC, pbelange commented
Sorry, getting used to git... I dit a git reset with a force pushed to not commit the extra files... I don't know if I need to open a new merge request?

2022-05-01 08:29 UTC, merged