Fixed non-symplecticity bug in LinearTransferMatrix
xsuite/xtrack pull request #271
Opened 2022-12-13 10:25 UTC by pkruyt

## Description

Closes # .

## Checklist

Mandatory: 

- [ ] I have added tests to cover my changes
- [ ] All the tests are passing, including my new ones
- [ ] I described my changes in this PR description

Optional:

- [ ] The code I wrote follows good style practices (see [PEP 8](https://peps.python.org/pep-0008/) and [PEP 20](https://peps.python.org/pep-0020/)).
- [ ] I have updated the docs in relation to my changes, if applicable
- [ ] I have tested also GPU contexts

2022-12-13 12:57 UTC, xbuffat commented
Ok for me!

2022-12-22 16:56 UTC, giadarol requested changes
Thank you very much for this PR. See below some comments.

In general, the publication you quote uses a different couple of conjugate variables for the longitudinal plane (delta, L=beta c t) compared to xsuite that uses (zeta=-beta0 c t, pzeta - see xsuite physics manual for the definitions). Note the swap (in the paper the momentum is L while for us it is pzeta). Moreover the paper assumes a drift in the longitudinal plane while in the xsuite element we have a rotation.

Could you please prepare a short latex document (on overleaf for example) where you adapt the derivation from the paper to our case?

This will allow checking that the proposed modification is correct.

Such a document could also be added as a section of the xsuite physics manual.

2022-12-22 16:56 UTC, giadarol commented on lineartransfermatrix.h
> +// copyright ############################### //
I believe this file is a duplicate and should be removed

2022-12-22 16:56 UTC, giadarol commented on xtrack/beam_elements/elements.py
> +class IonLaserIP(BeamElement):
I believe this element was added by mistake and should be removed (otherwise tests should be added)

2022-12-22 16:56 UTC, giadarol commented on xtrack/beam_elements/elements_src/lineartransfermatrix.h
> +    new_px -= disp_px_0 * delta + px_ref_0;
delta and zeta are not canonically conjugate. Using a symplectic matrix with these coordinates results in a non-symplectic map

2023-01-09 10:04 UTC, xbuffat commented
Indeed in the code we implemented a modified version of the matrix in the initial reference which was based on a different definition of the longitudinal variable. I changed the reference in the description to another one with the right convention. I would propose to merge this, as anyway I need to write the physics manual for this element. I will also integrate this part them.

2023-01-09 10:14 UTC, xbuffat commented
Actually it is still not exactly the same (in the non ultrarelativistic case). Let's redo the math then before we merge...

2023-01-19 16:05 UTC, xbuffat commented
I checked the math and added the missing beta ratios (rvv). I'll include the math when writing the doc for the entire element which is still missing.
There is an error that is generated by the energy_ref_increment that is linked to the fact that rvv is not properly updated in ducktrack (It was already there before, but remained unnoticed since in the tests rvv was not used). I suggest to fix this in a separate issue, for the moment I set it to 0 in the tests.

2023-03-21 08:11 UTC, closed without merging