Feature/electron cooler
xsuite/xtrack pull request #394
Opened 2023-09-11 13:05 UTC by pkruyt

Redid Pull request: Feature/electron cooler #335 

I have added an ElectronCooler beam element to Xtrack. The cooler uses the Parkhomchuk model.

## Checklist

Mandatory: 

- [x] I have added tests to cover my changes
- [x] All the tests are passing, including my new ones
- [x ] I described my changes in this PR description

Optional:

- [ ] The code I wrote follows good style practices (see [PEP 8](https://peps.python.org/pep-0008/) and [PEP 20](https://peps.python.org/pep-0020/)).
- [x ] I have updated the docs in relation to my changes, if applicable
- [ ] I have tested also GPU contexts

2023-09-11 13:07 UTC, pkruyt commented
Sorry for reopening the old pull request, but I was having some trouble with my vscode. The new test takes less time to run and it is ready to be merged.

2023-10-18 07:02 UTC, giadarol commented
Closed by mistake

2023-10-18 07:02 UTC, giadarol commented
Closed by mistake

2023-11-06 09:33 UTC, pkruyt commented
Fixed the merge conflicts and reran all the tests. All the tests passed so it is ready to be merged.

2024-04-19 14:47 UTC, pkruyt commented
Hey Gianni, 

Could you please review and merge this pull request? It would be convenient for others who are waiting to use electron cooler.

2025-01-21 15:47 UTC, giadarol requested changes

2025-01-21 15:47 UTC, giadarol commented on tests/test_elements.py
> +    assert np.allclose(pf.ptau, pfy.ptau, rtol=0, atol=1e-14)
Please go back to xo.assert_allclose

2025-01-21 15:47 UTC, giadarol commented on tests/test_elements.py
> +    data = np.load('../test_data/electron_cooler/emittance_betacool.npz')
To get the test data folder use the strategy here:
https://github.com/xsuite/xtrack/blob/43e6bddcfbaec9e53ae76d9007fc9cc771adc60c/tests/test_coasting.py#L8

https://github.com/xsuite/xtrack/blob/43e6bddcfbaec9e53ae76d9007fc9cc771adc60c/tests/test_coasting.py#L15

2025-01-21 15:47 UTC, giadarol commented on tests/test_elements.py
> +            # total_intensity_particles=bunch_intensity,
If not needed please remove

2025-01-21 15:47 UTC, giadarol commented on tests/test_elements.py
> +    for i in range(len(time_betacool) - 1, -1, -1):
Add a comment on what you are doing here

2025-01-21 15:47 UTC, giadarol commented on tests/test_elements.py
> +def test_ecooler(test_context):
Split test of force and test of element in two parts

2025-01-21 15:47 UTC, giadarol commented on xtrack/beam_elements/elements_src/electroncooler.h
> +void ElectronCooler_track_local_particle(ElectronCoolerData el, LocalParticle* part0){
If you want to save the force you can use the element internal record.
See: https://xsuite.readthedocs.io/en/latest/dev_guide_xtbe_internal_record.html

2025-03-31 11:18 UTC, merged